SYSTEM_NAME="geforcenow"
SYSTEM_FULLNAME="GeForce NOW"
SYSTEM_MANUFACTURER="&#xf013; System"
SYSTEM_RELEASE="System"
SYSTEM_HARDWARE="System"
SYSTEM_PATH="/storage/roms/geforcenow/"
SYSTEM_EXTENSION=".sh"
SYSTEM_COMMAND="/bin/sh %ROM%"
SYSTEM_PLATFORM="geforcenow"
SYSTEM_THEME="geforcenow"
SYSTEM_WIKI_PATH="geforcenow"
