# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 ROCKNIX (https://github.com/ROCKNIX)
#
# Perf Control - apply a profile to the hardware.
#
# This NEVER runs a background fan loop. The fan is driven by the ROCKNIX
# `fancontrol` systemd daemon; we only configure it (write fancontrol.conf +
# cooling.profile=custom + restart) exactly like the system does. That keeps
# the clean hand-off with the Steam/Decky plugin intact (the plugin stops the
# daemon to take over in Steam, and restarts it on exit).

import subprocess

import pc_config as C
import pc_hardware as hw


# --------------------------------------------------------------------------- #
# ROCKNIX settings + services (via the shell helpers in /etc/profile)
# --------------------------------------------------------------------------- #
def get_setting(key):
    try:
        out = subprocess.check_output(
            ["/bin/bash", "-c",
             'source /etc/profile >/dev/null 2>&1; get_setting "$1"', "_", key],
            stderr=subprocess.DEVNULL)
        return out.decode("utf-8", "replace").strip()
    except Exception:
        return ""


def set_setting(key, value):
    try:
        subprocess.call(
            ["/bin/bash", "-c",
             'source /etc/profile >/dev/null 2>&1; set_setting "$1" "$2"',
             "_", key, str(value)])
        return True
    except Exception:
        return False


def _systemctl(*args):
    try:
        subprocess.call(["systemctl"] + list(args),
                        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception:
        pass


# --------------------------------------------------------------------------- #
# fan curve -> fancontrol.conf
# --------------------------------------------------------------------------- #
def _curve_to_conf(curve):
    """Ascending {temps,speeds} -> descending SPEEDS()/TEMPS() the daemon wants.

    The daemon picks SPEEDS[i] at the first i where temp > TEMPS[i]. We append a
    final TEMPS=0 band whose speed equals the lowest point's speed, so cool temps
    hold the minimum fan speed (matching the plugin's clamp-below-first-point).
    """
    temps = curve.get("temps", [])
    speeds = curve.get("speeds", [])
    pairs = sorted(zip(temps, speeds))            # ascending by temp
    if not pairs:
        pairs = sorted(zip(C.DEFAULT_FAN_CURVE["temps"], C.DEFAULT_FAN_CURVE["speeds"]))
    desc = list(reversed(pairs))                  # descending by temp
    t_arr = [int(t) for t, _ in desc] + [0]
    s_arr = [_clamp_pwm(s) for _, s in desc] + [_clamp_pwm(desc[-1][1])]
    return t_arr, s_arr


def _clamp_pwm(v):
    try:
        v = int(v)
    except (TypeError, ValueError):
        return 0
    return max(0, min(C.PWM_MAX, v))


def _write_fancontrol_conf(t_arr, s_arr):
    body = (
        "# Generated by Perf Control (ROCKNIX). Shared with the Steam/Decky\n"
        "# plugin via cooling.profile=custom. Edit via the Perf Control tool.\n"
        "DEBUG=false\n"
        "SPEEDS=(%s)\n"
        "TEMPS=(%s)\n" % (" ".join(str(x) for x in s_arr),
                          " ".join(str(x) for x in t_arr))
    )
    try:
        with open(C.FANCONTROL_CONF, "w") as fh:
            fh.write(body)
        return True
    except Exception as exc:
        C.log("FAILED to write %s: %s" % (C.FANCONTROL_CONF, exc))
        return False


def apply_fan(profile, restart=True):
    mode = profile.get("fan_mode", "auto")
    if mode == "curve":
        t_arr, s_arr = _curve_to_conf(profile.get("fan_curve", C.DEFAULT_FAN_CURVE))
        _write_fancontrol_conf(t_arr, s_arr)
        set_setting(C.COOLING_PROFILE_KEY, "custom")
    elif mode == "fixed":
        pwm = _clamp_pwm(profile.get("fan_pwm", 0))
        # constant speed: any temp falls through to the terminator band
        _write_fancontrol_conf([150000, 0], [pwm, pwm])
        set_setting(C.COOLING_PROFILE_KEY, "custom")
    else:  # auto -> hand back to a stock named profile
        set_setting(C.COOLING_PROFILE_KEY, "moderate")
    if restart:
        _systemctl("restart", "fancontrol")


# --------------------------------------------------------------------------- #
# clocks
# --------------------------------------------------------------------------- #
def apply_caps(profile):
    policies = hw.list_cpu_policies()
    govs = hw.available_governors()
    for pol in policies:
        num = pol["num"]
        fmax = profile.get("cpu_policy%d_max" % num)
        fmin = profile.get("cpu_policy%d_min" % num)
        if fmax is not None or fmin is not None:
            hw.set_cpu_policy(num, fmin=fmin, fmax=fmax)
    gov = profile.get("governor")
    if gov and gov in govs:
        for pol in policies:
            hw.set_cpu_governor(pol["num"], gov)

    gmax = profile.get("gpu_max")
    gmin = profile.get("gpu_min")
    if gmax is not None or gmin is not None:
        hw.set_gpu(fmin=gmin, fmax=gmax)
        _reconcile_gpu_oc(gmax)


def _reconcile_gpu_oc(gmax):
    """Avoid the boot-time gpu_overclock quirk fighting a profile's GPU cap.

    `enable.gpu-overclock=1` makes ROCKNIX force the GPU max to its OC value at
    boot. If a profile clamps the GPU below that, clear the OC flag so our cap
    is the one that sticks across reboots.
    """
    if gmax is None:
        return
    try:
        if get_setting(C.GPU_OC_KEY) == "1":
            gpu = hw.find_gpu()
            oc_top = gpu["avail"][-1] if (gpu and gpu["avail"]) else None
            if oc_top is not None and int(gmax) < oc_top:
                set_setting(C.GPU_OC_KEY, "0")
                C.log("cleared %s (profile clamps GPU below OC top)" % C.GPU_OC_KEY)
    except Exception:
        pass


# --------------------------------------------------------------------------- #
# public entry points
# --------------------------------------------------------------------------- #
def apply_profile(profile, fan=True):
    apply_caps(profile)
    if fan:
        apply_fan(profile, restart=True)


def reset_default():
    for pol in hw.list_cpu_policies():
        hw.reset_cpu_policy(pol["num"])
    hw.reset_gpu()
    set_setting(C.COOLING_PROFILE_KEY, "moderate")
    _systemctl("restart", "fancontrol")
